version: 2.1

orbs:
  python: circleci/python@1.5.0
  docker: circleci/docker@1.7.0
  browser-tools: circleci/browser-tools@1.2.3
  codecov: codecov/codecov@3.1.1

jobs:
  unit-tests:
    docker:
      - image: cimg/python:3.10.2

    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pip

      - run:
          name: Run tests
          command:   |
            mkdir test-results
            pytest --junitxml=test-results/junit.xml

      - store_test_results:
          path: test-results

  code-coverage:
    docker:
      - image: cimg/python:3.10-browsers
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pip

      - run:
          name: Run tests

          command:   |
            coverage run -m pytest
            coverage report
            coverage html
            coverage xml

      - store_artifacts:
          path: htmlcov

      - codecov/upload:
          file: coverage.xml

  build-docker-image:
    executor: docker/docker
    steps:
      - setup_remote_docker

      - run:
          name: Docker login
          command: |
            echo "$DOCKER_PASS" | docker login -u "$DOCKER_USER" --password-stdin

      - checkout

      - docker/build:
          image: hit-counter
          tag: latest
          registry: robinmeyssonnier

      - docker/push:
          image: hit-counter
          registry: robinmeyssonnier
          tag: latest


workflows:
  hitcount-ci-cd:
    jobs:
      - unit-tests
      - code-coverage:
          requires:
            - unit-tests
      - build-docker-image:
          requires:
            - code-coverage