---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hitcounter-deployment
spec:
  selector:
    matchLabels:
      app: hitcounter
  replicas: 2
  template:
    metadata:
      labels:
        app: hitcounter
    spec:
      containers:
      - name: hitcounter
        image: docker.io/robinmeyssonnier/hit-counter:latest
        ports:
        - containerPort: 34001
---
apiVersion: v1
kind: Service
metadata:
  name: hitcounter-service
spec:
  selector:
    app: hitcounter
  type: NodePort
  ports:
    - port: 34001
      targetPort: 34001
      nodePort: 32000
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: hitcounter-ingress
  labels:
    name: hitcounter-ingress
spec:
  rules:
  - host: hit-counter.local
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: hitcounter-service
            port:
              number: 34001